### ISSUE TITLE
Using milestones for releases?

### ISSUE THREAD

**Issue by NiteshKant** [ReactiveSocket/reactivesocket-java#111]
#### Problem (kind of)

Currently, we have an ad-hoc process of release i.e. we release when we feel like 😄 

#### Solution

Have github milestones to indicate when master is ready for release. 
This will give better insight to people as to when can they expect a release.

I have created [two](https://github.com/ReactiveSocket/reactivesocket-java/milestones/0.2.2) [milestones](https://github.com/ReactiveSocket/reactivesocket-java/milestones/0.2.3) for now, hoping everyone agrees :)

**Comment by stevegury** [comment]
👍

**Comment by NiteshKant** [comment]
\cc @rdegnan @robertroeser

**Comment by NiteshKant** [comment]
Cool, closing this one then.
