### ISSUE TITLE
Calling cancel() before request(n) causes null pointer exception

### ISSUE THREAD

**Issue by xytosis** [ReactiveSocket/reactivesocket-java#132]
While writing the TCK for reactive sockets, my TCK code found the bug mentioned above.

```
val s4 = requestResponse("g", "h")
    s4 cancel()
    s4 assertCanceled()
    s4 assertNoErrors()
    s4 assertNotCompleted()
    s4 assertReceivedCount 0
```

The line `s4 cancel()` causes the NPE on the client side, as it seems like the current implementation always expects request(n) to be called before cancel.

**Comment by NiteshKant** [comment]
PR #133 addresses this issue PTAL.

**Comment by NiteshKant** [comment]
@xytosis if this is not blocking you, I will like to wait for one more person (thanks @yschimke for the review) to review it before merging. @stevegury should be in next week, when we can merge the fix.

**Comment by xytosis** [comment]
@NiteshKant no worries, this isn't blocking me at all. I can continue to work on the TCK independently of any bugs.
