### ISSUE TITLE
Depend on `1.0.0` of ReactiveStreams

### ISSUE THREAD

**Issue by ktoso** [ReactiveSocket/reactivesocket-java#138]
I noticed the project is depending on `compile 'org.reactivestreams:reactive-streams:1.0.0.final'` which "works".

However has some weird corner cases (esp. around OSGi, not that I personally care, but downstream consumers of such libs may care). It is the exact same bytes as `1.0.0`, however ordering of `-RC` vs. `.final` behaves weirdly in some contexts, `1.0.0` is safe everywhere, so that version should be prefered.

**Comment by NiteshKant** [comment]
Closed via #139
