### ISSUE TITLE
`RequestHandler` returning `Publisher<T>`

### ISSUE THREAD

**Issue by NiteshKant** [ReactiveSocket/reactivesocket-java#14]
I have not thought about it much but on the face of it, looks like it will be better to move to RxNetty's established model of returning a `Publisher<Void>`. The drawback of returning `Publisher<T>`  is that we loose feedback from the write to the stream.

**Comment by benjchristensen** [comment]
Is this still an issue to discuss?

**Comment by stevegury** [comment]
I'm not sure to understand the question, RequestHandler interaction model is defined with:

```
public abstract Publisher<Payload> handleRequestResponse(final Payload payload);
public abstract Publisher<Payload> handleRequestStream(final Payload payload);
public abstract Publisher<Payload> handleSubscription(final Payload payload);
public abstract Publisher<Void> handleFireAndForget(final Payload payload);
```

Which returns Publisher<T> when required and Publisher<Void> otherwise.
