### ISSUE TITLE
ReactiveSocket server handler evaluates RequestHandler code lazily

### ISSUE THREAD

**Issue by xytosis** [ReactiveSocket/reactivesocket-java#159]
While trying to implement concurrent tests for the TCK, I found that the lazily evaluation of the RequestHandler (the code gets evaluated during runtime upon the first request to the server) could cause the server to throw a NPE during many concurrent initial requests, as some of the data structures that some requests require are not initialized yet. While it probably is possible to write code in a way that this doesn't happen, it still seems rather dangerous that this can happen at all.

**Comment by yschimke** [comment]
Can you reproduce in a test case?

**Comment by xytosis** [comment]
Sorry for the late response, was deciding what was the best way to do so.

If you go into the JavaClientDriver and look at the `runTests()` method, and comment out the line `thread.join()` and then run the TCK with the server and client (the server should be freshly started up) with the `clienttest$.txt` and `servertest$.txt` files, the client will fire all its tests at once, and there will be some NPEs in the console.
This is because the initialization of all the handlers requires parsing through the `servertest$.txt` file, and it's getting requests faster than it can parse through the file, so some handlers may not be fully initialized.

**Comment by yschimke** [comment]
I think it is worth getting this reproduced without the full TCK running based on what you described.  But even a failing TCK example as you describe would be useful for whoever looks at the issue.  Make a test branch with changes to reproduce and link to it.

**Comment by xytosis** [comment]
I'll make a trivial example that would still fail, which wouldn't use the TCK, and I can do so on my own fork and link to it. I'll work on this a bit later today.

**Comment by xytosis** [comment]
I'm unable to recreate this without the TCK, so it might be specific to the way my code is being written. I'll close the issue for now.
