### ISSUE TITLE
NPE on UnicastSubject's onNext() method

### ISSUE THREAD

**Issue by xytosis** [ReactiveSocket/reactivesocket-java#162]
I found this bug while writing tests with my TCK.
If we request Stream or Subscription, and then call request(n) and then immediately cancel() without awaiting for the value to come, and we do this multiple times, we will get a NPE in Unicast Subject's onNext() function, because for some reason the subscriber inside is null.
An repro of this bug can be found in my fork here: https://github.com/xytosis/reactivesocket-java/tree/failing_tests/reactivesocket-tck-drivers
The failing client/server is inside a package called `fail`. Simply open in Intellij, run the server, and then run the client.

**Comment by xytosis** [comment]
This bug seems to have multiple causes, and I am still in the process of trying to find them. One cause (which might be the reason behind the previous cause I found) occurs when we create a ReactiveSocket, requestStream with it, request some amount and then cancel without waiting for that item to come, and then immediately use the same instance of ReactiveSocket to create another requestStream or requestSubscription and then request and immediately cancel again without awaiting, we get this NPE.

**Comment by xytosis** [comment]
I pushed another case of this bug to my branch. It seems like using the same reactivesocket instance is dangerous, because in this case, if we create a stream and then subscribe, and the immediately do it again and we send some requests, we run into the same NPE in UnicastSubject.

**Comment by yschimke** [comment]
@xytosis in your repro I'm suspicious of these lines

        TestSubscriber<Payload> ts = new TestSubscriber<>(0L);
        Publisher<Payload> pub = r.requestStream(new PayloadImpl("a", "b"));
        pub.subscribe(ts);
        ts.request(1);
        ts.cancel();

TestSubscriber is a subscriber obviously, but you are using methods which come from it implementing Subscription also.  in this case, I don't think they are intended for you to call this way.

**Comment by xytosis** [comment]
@yschimke It's true TestSubscriber implements Subscription as well as Subscriber, but it itself is not a subscription object. Instead, it stores the subscription object it receives from `onSubscribe`, and when calling `request(n)` on TestSubscriber calls `request` on the internal subscription object. It's just for convenience sake, and the interaction should be valid.

**Comment by yschimke** [comment]
I'd suggest not implementing the Subscription interface, just having the methods with the same name.

**Comment by yschimke** [comment]
The race condition is clearer in the success case.  Your "main" thread is racing a response on the netty thread "rxnetty-nio-eventloop-1-1".

```
815992954 subscribe (&set) io.reactivesocket.internal.Requester$StreamInputSubscriber@33c7e1bb main
1650560446 subscribe (&set) rx.internal.reactivestreams.SubscriberAdapter@1c5d70ed rxnetty-nio-eventloop-1-1
1650560446 onNext (&get) rx.internal.reactivestreams.SubscriberAdapter@1c5d70ed main
1650560446 onNext (&get) rx.internal.reactivestreams.SubscriberAdapter@1c5d70ed rxnetty-nio-eventloop-1-1
1650560446 onNext (&get) rx.internal.reactivestreams.SubscriberAdapter@1c5d70ed main
```

UnicastSubject which is created inside the Requester is documented as *not* thread safe.  So I'm unclear how a Subscription can be safely cancelled by an Application thread, not in response and inline with an event received on the network. It seems like what you are doing should be possible.

**Comment by xytosis** [comment]
@yschimke I copied TestSubscriber from RxJava, so I'm not sure why implementing both interfaces is a "bad" thing.

On the race condition, I see what you mean. However, it seems like cancel would mostly be used by application threads and not inline networking threads, so perhaps the UnicastSubject should be made to be thread safe?

**Comment by yschimke** [comment]
The next obvious question is whether copying a large class like TestObserver into here is good idea. That class is pretty actively maintained upstream.

But generally a Subscriber is given a subscription, I would have argued for asking TestSubscriber for its subscription if any.  But I defer to the maintainers in their wisdom.

**Comment by xytosis** [comment]
@yschimke It wasn't a direct copy paste, I removed a lot of the unnecessary code and kept the core functionality. They hold the subscription inside TestSubscriber, and they also do it with an AtomicReference to make things thread safe, and hold all `request(n)` until the subscription has arrived. I'm not sure why they implemented subscription either, maybe it's some sort of obscure Java convention.

**Comment by benjchristensen** [comment]
The pattern followed with `TestSubscriber` makes sense to me and I suggested Martin do it for the TCK. He needed similar behavior as `TestSubscriber`, but specialized for the TCK. Nothing about it should affect concurrency.

>  I'm suspicious of these lines

It does indeed look suspicious at first glance, however, `TestSubscriber` handles this race internally (not atomically based on my review of the code, but it won't cause an NPE). Also, the stacktrace shows it is not the issue with the `TestSubscriber.request` method. 

It does seem like a bug that an NPE is thrown from inside `UnicastSubject`. The usage by Martin is all synchronous method invocation, I don't see him adding any extra concurrency. 

Code here: https://github.com/xytosis/reactivesocket-java/blob/e4d7517f2b619a52ef6ad97a96412eaf37ec85ed/reactivesocket-tck-drivers/src/main/java/io/reactivesocket/tckdrivers/fail/ClientActor.java#L41

```java
ReactiveSocket r = Client.createClient();
        TestSubscriber<Payload> t1 = new TestSubscriber<>(0L);
        Publisher<Payload> p1 = r.requestStream(new PayloadImpl("a", "b"));
        p1.subscribe(t1);
        TestSubscriber<Payload> t2 = new TestSubscriber<>(0L);
        Publisher<Payload> p2 = r.requestStream(new PayloadImpl("c", "d"));
        p2.subscribe(t2);
        t1.request(1);
        t2.request(2);
        t1.request(1);
        t2.request(1);
        t1.request(1);
```

That is just making two `requestStream` calls on a single `ReactiveSocket` instance. It should have two async/concurrent streams. 

Thus, a single `ReactiveSocket` instance should be safe to use for multiple async requests.

**Comment by xytosis** [comment]
@yschimke from a cursory glance at the code, Ben and I agree this is an issue.

I'd like to know what can be done to fix this, it seems like a more far reaching issue than the previous bug I've found. Making UnicastSubject thread safe would do, but that would lead to some inefficiency. Perhaps there could be some sort of AysncUnicastSubject that can be specified for a reactive socket to use, and this option can be set using some sort of flag in it's construction?

**Comment by NiteshKant** [comment]
@xytosis @yschimke @benjchristensen 
FYI: At Netflix we are working at a very large scale refactoring of the reactivesocket-java code which will discontinue this class as well, so unless this is blocking you from moving forward, I would suggest not to spend time on it.

**Comment by xytosis** [comment]
@NiteshKant it's not particularly blocking, but it does mean that some tests that *should* pass are failing and may potentially block continued testing of the CPP impl depending on how fast the FB people move on that. But I think everything should be fine for now.

Will the new refactor change any of the external APIs? If so, let me know and I can update the TCK drivers accordingly.

**Comment by NiteshKant** [comment]
>> Will the new refactor change any of the external APIs? If so, let me know and I can update the TCK drivers accordingly.

Not quiet sure as yet, but we will update the drivers since they are in the -java repo.
