### ISSUE TITLE
what is the maximum value for initialRequestN?

### ISSUE THREAD

**Issue by yschimke** [ReactiveSocket/reactivesocket-java#172]
From https://github.com/ReactiveSocket/reactivesocket/blob/master/Protocol.md

> Request N: integer value of items to request.

With a java hat on, the max value is clearly Integer.MAX_VALUE.  Is that correct?  Should we update the protocol to be more definitive?

**Comment by NiteshKant** [comment]
you mean specify that it is a 32 bit number?

**Comment by robertroeser** [comment]
The ascii frame shows it's 32-bit which is an integer in java.

**Comment by yschimke** [comment]
So we had an issue with cpp (client) talking to java (server) because uint32 max is negative as a Java int.  A went to the protocol doc to clarify, didn't get a clear answer there.  So I checked the Java code, saw a long at first but after more digging found a (signed) int.

```
reactivesocket-core/src/main/java/io/reactivesocket/Frame.java:        public static long initialRequestN(final Frame frame) {
reactivesocket-core/src/main/java/io/reactivesocket/internal/frame/RequestFrameFlyweight.java:        final int initialRequestN,
```

**Comment by robertroeser** [comment]
Ok I kind figured thats where this was going. I added a method internally on the RequestFrameFlyWeight to deal with this.

@tmontgomery 
could we reserve the first bit so it's never negative?

**Comment by yschimke** [comment]
This looks consistent now, spec + code in RequestFrameFlyweight
