### ISSUE TITLE
Remove branch `master`?

### ISSUE THREAD

**Issue by NiteshKant** [ReactiveSocket/reactivesocket-java#177]
Code from current master is in branch [0.2.x](https://github.com/ReactiveSocket/reactivesocket-java/tree/0.2.x) and the next version code is in branch [0.5.x](https://github.com/ReactiveSocket/reactivesocket-java/tree/0.5.x).

IMO, the existence of a branch named `master` is sort of confusing when we are working on two different versions. So, should we delete `master` branch and just have two 0.2.x and 0.5.x branches? 

After deletion of `master`, 0.2.x will be the default branch till 0.5.x is stable.

**Comment by ktoso** [comment]
Sure, I don't mind. 
At this phase of the project we don't have any strong guarantees about compatibility anyway do we?
Just want to make sure we use the same meanings for the version numbers :)

**Comment by NiteshKant** [comment]
@ktoso yep there are no strong compatibility guarantees.

>> Just want to make sure we use the same meanings for the version numbers

The current versioning scheme sounds ok to you?

**Comment by yschimke** [comment]
@NiteshKant will travis build both new master branches?

**Comment by NiteshKant** [comment]
@yschimke I would say once, `0.5.x` is ready for release, we would no longer require `0.2.x`. 
Assuming we update all related projects (tck and cli) with `0.5.x`'s first release, is there a reason we would need to build both?

**Comment by yschimke** [comment]
Probably not, just assumes that 0.2.x is complete, and 0.5.x is close to ready.  No issue from me.

**Comment by NiteshKant** [comment]
Removed `master` branch. Thanks guys!
