### ISSUE TITLE
Snapshots and Releases

### ISSUE THREAD

**Issue by benjchristensen** [ReactiveSocket/reactivesocket-java#222]
I got releases flowing to Maven Central today: http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22io.reactivesocket%22

My changes also affected snapshots, which are now publishing based on the next tagged version. For example: https://oss.jfrog.org/libs-snapshot/io/reactivesocket/reactivesocket-core/0.5.3-SNAPSHOT/

Do you want it working like this (the default behavior of the plugin) where it uploads snapshots with the next version number and the SNAPSHOT suffix?

Or do you want me to put it back to always releasing a 0.5.0 snapshot, regardless of the released version?

Now that we are releasing to maven central, I think it's better to have it showing the snapshot for the next release. 

So right now, 0.5.2 is on Maven Central, and it's publishing 0.5.3-SNAPSHOT as the snapshot.

**Comment by NiteshKant** [comment]
@benjchristensen Yay and thanks!

This is perfect publishing the next version snapshot after a release is what makes sense.

**Comment by ktoso** [comment]
Very cool, thanks for the releases on central! :-)
