### ISSUE TITLE
missing backpressure exception (across TCP connection)

### ISSUE THREAD

**Issue by rkuhn** [ReactiveSocket/reactivesocket-java#229]
When streaming a response at maximum speed and using `observeOn` on the client side a MissingBackpressureException is observed. For a runnable demonstration please see https://gist.github.com/rkuhn/e450772db7ecc0c52be7e3c78d528973

**Comment by NiteshKant** [comment]
@rkuhn It sure looks like a bug in the backpressure code, not sure yet whether it is in RxJava or ReactiveSocket side of things, I will keep digging.

**Comment by rkuhn** [comment]
My first thought was some race in disabling reception on the Netty layer leading to the arrival of an unrequested message, but it is just an unsubstantiated guess. Thanks for digging!

**Comment by NiteshKant** [comment]
@rkuhn I updated your code to print requested and emitted counts on client and server and it appears to me that there is a bug in RxJava (`observeOn` potentially). Both client and server did not show a mismatch in requested and emitted. Here is the [gist](https://gist.github.com/NiteshKant/9bf665902815a1209bdda228ebbbd866) with my changes.

**Comment by rkuhn** [comment]
Yes, it seems to point in that direction. I’ll try to reproduce without ReactiveSocket.

**Comment by rkuhn** [comment]
After trying several variations without involving ReactiveSocket I find myself unable to reproduce the issue. I have replaced

~~~scala
Flowable.fromPublisher(socket.requestSubscription(new PayloadImpl(request)))
~~~

with

~~~scala
Flowable.<Payload>generate(emitter -> emitter.onNext(new PayloadImpl("hello")))
          .observeOn(Schedulers.single(), false, 16)
~~~

and played with different buffer sizes up to 4096—I have also tried without the `.observeOn` but I think that the timing of the upstream source must have something to do with the error, so it should probably not be synchronous.

My preliminary conclusion is that the error must be somewhere below [this line of the stack trace](https://gist.github.com/rkuhn/e450772db7ecc0c52be7e3c78d528973#file-exception-txt-L77).

**Comment by benjchristensen** [comment]
@robertroeser and I were talking about this and think it's worth trying an implementation with Pivotal Reactor as the API for Netty rather than RxNetty. The RxNetty codebase does not have sufficient investment and we think the problem is in that bridge.

**Comment by robertroeser** [comment]
Yep - we're working on replace the internals with reactor-core, and reactor-netty, and there should be a pull request shorty as fix some remaining bugs.

**Comment by rkuhn** [comment]
Thanks for the update!

**Comment by robertroeser** [comment]
@rkuhn - I tried running you code with after the reactor pull request and I got the same issue as before. However, I think the problem was with observerOn. I removed it and it looks like the test is now working:
https://gist.github.com/robertroeser/695b6f4b48183d1efa741b7ebdb6c2de


Thanks,
Robert

**Comment by robertroeser** [comment]
Might need to do some more checking - added - .publishOn(Schedulers.single()) and got the same thing
