### ISSUE TITLE
Lost Perf with Setup Frame

### ISSUE THREAD

**Issue by benjchristensen** [ReactiveSocket/reactivesocket-java#24]
We somehow lost perf when adding the Setup Frame. I would expect some loss per connection, but the perf test is a single connection, so I wouldn't expect to see the cost of a single extra frame. Thus, it seems something about the setup processing has affected it for every message.

We went from ~3.5m to ~3.1m request/response per second.

**Comment by benjchristensen** [comment]
FrameType.from is consistently sampled to be the hottest method.

<img width="1075" alt="screen shot 2015-08-26 at 12 03 52 pm" src="https://cloud.githubusercontent.com/assets/813492/9503230/8d4d112e-4bea-11e5-9c4f-05dc3023e58f.png">

**Comment by tmontgomery** [comment]
It might be that extending the frame type values makes the array too long and keeps the method from being inlined for some reason. Try to redefine the values to be totally sequential to make the array smaller and see what happens.

**Comment by benjchristensen** [comment]
Dealt with.
