### ISSUE TITLE
Publish 1.0.x branch snapshots to jfrog

### ISSUE THREAD

**Issue by yschimke** [ReactiveSocket/reactivesocket-java#251]

**Comment by yschimke** [comment]
brainfart - checking the snapshot repository

**Comment by yschimke** [comment]
https://oss.jfrog.org/artifactory/libs-snapshot/io/reactivesocket/reactivesocket-core/

**Comment by benjchristensen** [comment]
Looks like it's publishing them, inferring v0.5.3.x which is correct right now:

https://travis-ci.org/ReactiveSocket/reactivesocket-java/builds/207446702#L419

I'll update the version.

**Comment by benjchristensen** [comment]
Published as 0.9-SNAPSHOT: https://oss.jfrog.org/artifactory/libs-snapshot/io/reactivesocket/reactivesocket-core/0.9-SNAPSHOT/

Config here: https://github.com/ReactiveSocket/reactivesocket-java/blob/1.0.x/gradle.properties

Left as 0.9 instead of 1.0 for now so we don't end up with 1.0.0-RC-1/2/3/.../23 before calling it 1.0.0 FINAL.

**Comment by yschimke** [comment]
I thought one of the gradle plugins was meant to use the branch name to decide the snapshot and release version?

**Comment by benjchristensen** [comment]
Without the property override it defaults to the last released version and increments by one. It gets that from the last tag. So this branch hasn't had a release yet so the last tag was still 0.5.x.

**Comment by benjchristensen** [comment]
Release versions come from the tag name. Nothing to do with the branch name.

**Comment by yschimke** [comment]
The prosecution introduce exhibit A:

// support for snapshot/final releases via versioned branch names like 1.x
nebulaRelease {
    addReleaseBranchPattern(/\d+\.\d+\.\d+/)
    addReleaseBranchPattern('HEAD')
}

**Comment by benjchristensen** [comment]
That is to allow releases from these branches.
