### ISSUE TITLE
How do we want logging?

### ISSUE THREAD

**Issue by yschimke** [ReactiveSocket/reactivesocket-java#254]
After the reactor change, the built in logging is now hexdumps instead of Frame.toString

```
         +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 00 00 39 00 00 00 00 04 20 00 01 00 00 7f ff ff |..9..... .......|
|00000010| ff 7f ff ff fd 10 61 70 70 6c 69 63 61 74 69 6f |......applicatio|
|00000020| 6e 2f 6a 73 6f 6e 12 61 70 70 6c 69 63 61 74 69 |n/json.applicati|
|00000030| 6f 6e 2f 62 69 6e 61 72 79                      |on/binary       |
+--------+-------------------------------------------------+----------------+
09:50:51.768	[id: 0x25c7fc8e, L:/127.0.0.1:50447 - R:localhost/127.0.0.1:9898] FLUSH
```

**Comment by robertroeser** [comment]
@yschimke there never really was built-in logging in ReactiveSocket. It was a Netty handler that printed frames. If we want to log reactive socket frames that should happen somewhere in the core package - probably in the DuplexConnection. The ClientServerInputMultiplexer would be a good place to do this as you could add context about if the frame was from a client, server, stream 0, etc.
