### ISSUE TITLE
Fragmentation & Reassembly

### ISSUE THREAD

**Issue by benjchristensen** [ReactiveSocket/reactivesocket-java#61]
Need to support fragmentation and reassembly.

**Comment by benjchristensen** [comment]
We need to decide on fragmentation of requests: https://github.com/ReactiveSocket/reactivesocket/issues/77

Right now the protocol only allows fragmenting responses.

**Comment by tmontgomery** [comment]
REQUEST_CHANNEL can be fragmented. At least it is specified in the frame that it has an F flag. Also, the fragmenter impl should support it. Off hand, not sure about the reassembler, but it should be easy to account for.

**Comment by benjchristensen** [comment]
Right, REQUEST_CHANNEL does, so it's the other 4 REQUEST types.

**Comment by tmontgomery** [comment]
Ah ok. I will add that to the spec in the next couple days.

**Comment by benjchristensen** [comment]
Thanks Todd

**Comment by benjchristensen** [comment]
A possible implementation of response fragmentation and reassembly is in pull request https://github.com/ReactiveSocket/reactivesocket-java/pull/63
