### ISSUE TITLE
Tear Down and Resource Cleanup

### ISSUE THREAD

**Issue by benjchristensen** [ReactiveSocket/reactivesocket-java#65]
I have little confidence in everything being properly connected for clean tear down when a connection closes, or when an error occurs. Need to unit test and prove resources are released or cleaned up.

**Comment by NiteshKant** [comment]
@stevegury I think this is fixed by #107 ?

**Comment by stevegury** [comment]
Yes, but it still lacks unit-tests.

**Comment by NiteshKant** [comment]
0.5.x handles underlying connection close correctly. Closing this issue.
