### ISSUE TITLE
io.reactivesocket.rx.* package

### ISSUE THREAD

**Issue by benjchristensen** [ReactiveSocket/reactivesocket-java#67]
I'm not thrilled about this package existing: https://github.com/ReactiveSocket/reactivesocket-java/tree/master/src/main/java/io/reactivesocket/rx

The `Completable` is useful, but I don't yet know if it will make it into RxJava v2. Where should that type go?

As for the `Observable` types, it would be better to use RxJava v2 at some point if these exist. Or can we somehow use just the java.util.function.Consumer<T> class for these use cases? I haven't convinced myself yet whether we actually need the `onError`/`onComplete` terminal events on this, as the only reason we use it is to expose `DuplexConnection.getInput`, and that should never invoke `onComplete`. A connection can fail, but perhaps we should have a different way of signaling that, since an error should affect the entire connection, not just input or output.

**Comment by NiteshKant** [comment]
0.5.x gets rid of this package. Closing.
