### ISSUE TITLE
DuplexConnection

### ISSUE THREAD

**Issue by benjchristensen** [ReactiveSocket/reactivesocket-java#7]
I have modeled this after our learning from RxNetty, particularly the `Publisher<Void> write(Publisher<Message> m)` API which supports backpressure as we hook into async IO, such as Netty and Aeron.

1) @niteshkant can you please confirm this is all done correctly as per your learnings with RxNetty?
2) What should we call this thing?

https://github.com/ReactiveSocket/reactivesocket-java/blob/e38b757ca02e597712139dfb9d01ba5dc7079c40/src/main/java/io/reactivesocket/DuplexConnection.java#L24

`Connection`? `SocketConnection`? `ReactiveSocketConnection`? Leave it as `DuplexConnection`?

**Comment by NiteshKant** [comment]
>> What should we call this thing?

How about calling it `ReactiveSocket` itself :) as it is one!

The `getInput()` and `write` methods look good. Should we be having a `close` method here too?

**Comment by benjchristensen** [comment]
We changed it. It's working.
