### ISSUE TITLE
Publish to Maven Central Repository

### ISSUE THREAD

**Issue by vjn** [ReactiveSocket/reactivesocket-java#71]
I would find it convenient to just download from Maven. Thanks!

**Comment by stevegury** [comment]
The problem is actually coming from the synchronization between bintray and maven central.
I need to look more into this.

For reference, here's the error in the bintray interface.
```
Last Sync Errors: No public key: Key with id: (93f9de56b3b1d69d) was not able to be located on <a href="http://keyserver.ubuntu.com:11371">http://keyserver.ubuntu.com:11371</a>. 
Upload your public key and try the operation again. 
No public key: Key with id: (93f9de56b3b1d69d) was not able to be located on <a href="http://pool.sks-keyservers.net:11371/">http://pool.sks-keyservers.net:11371/</a>. 
Upload your public key and try the operation again. 
No public key: Key with id: (93f9de56b3b1d69d) was not able to be located on <a href="http://pgp.mit.edu:11371/">http://pgp.mit.edu:11371/</a>. 
Upload your public key and try the operation again. 
Dropping existing partial staging repository.
```

**Comment by benjchristensen** [comment]
I'm confused. I just put the public and private keys in the Bintray account, and even re-release (v0.0.3) so it had a chance to sign the files on upload, and it is still having the issue. 

After 45 minutes of messing with this I have run out of time and am not finding what needs to be fixed :-/

**Comment by stevegury** [comment]
Same here, my understanding of the error is that the pgp public key used to sign the jar is not published anywhere (keyserver.ubuntu.com, pgp.mit.edu are the main repos).
I have no idea how the signing is made and where the key is found.

**Comment by electrum** [comment]
It's easy to publish directly to Maven Central: http://central.sonatype.org/pages/ossrh-guide.html

**Comment by yschimke** [comment]
*ping*

I've published these previously as snapshots under my own groupId to sonatype, and could publish as releases (I do for other projects) to maven central.  But the right fix must be getting this set up cleanly with reactivesocket-project, not the ossrh guide.  I don't think I can do that.

**Comment by stevegury** [comment]
We have involved our eng-tools team to see why the gradle plugin is not working.
They're working on it.

**Comment by yschimke** [comment]
Awesome to know. We will work around for now. Thanks!

**Comment by yschimke** [comment]
https://mvnrepository.com/artifact/io.reactivesocket/reactivesocket-core

thanks @benjchristensen
